var htmlTemplate = [
    '<div class="cubelet-cube">'
      ,'<figure class="cubelet-front"></figure>'
      ,'<figure class="cubelet-back"></figure>'
      ,'<figure class="cubelet-right"></figure>'
      ,'<figure class="cubelet-left"></figure>'
      ,'<figure class="cubelet-top"></figure>'
      ,'<figure class="cubelet-bottom"></figure>'
    ,'</div>'
  ].join('');


var cssTemplate = [
    '.cubelet { '
      ,'margin: 0 auto; }'
    ,'.cubelet-cube { '
      ,'__VENDOR__transform: translateZ(-100px) rotateY(0deg) rotateX(0deg); '
      ,'__VENDOR__transform-style: preserve-3d;'
      ,'height: 100%;'
      ,'width: 100%; }'
    ,'.cubelet-cube figure {'
      ,'margin: 0;'
      ,'position: absolute;'
      ,'height: 100%;'
      ,'width: 100%; }'
    ,'.cubelet-front {'
      ,'__VENDOR__transform: rotateY(   0deg ) translateZ( 100px ); }'
    ,'.cubelet-back {'
      ,'__VENDOR__transform: rotateX( 180deg ) translateZ( 100px );'
      ,'background: #fb0; }'
    ,'.cubelet-right {'
      ,'__VENDOR__transform: rotateY(  90deg ) translateZ( 100px );'
      ,'background: #00cc4e; }'
    ,'.cubelet-left {'
      ,'__VENDOR__transform: rotateY( -90deg ) translateZ( 100px );'
      ,'background: #06f; }'
    ,'.cubelet-top {'
      ,'__VENDOR__transform: rotateX(  90deg ) translateZ( 100px );'
      ,'background: #f77; }'
    ,'.cubelet-bottom {'
      ,'__VENDOR__transform: rotateX( -90deg ) translateZ( 100px );'
      ,'background: #b00; }'
].join('\n');
